{% set name = "bunnet" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bunnet-{{ version }}.tar.gz
  sha256: 5e4aeee9c30ac7fe3968ad057398349d8c3fb886c5b568980266fc4e061c3a8f

build:
  entry_points:
    - bunnet = bunnet.executors.migrate:migrations
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core
    - pip
  run:
    - click >=7
    - lazy-model >=0.2.0
    - pydantic >=1.10.0,<3
    - pymongo >=3
    - python >={{ python_min }}
    - toml

test:
  imports:
    - bunnet
  commands:
    - pip check
    - bunnet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/roman-right/bunnet
  summary: Synchronous Python ODM for MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
